export const VERIFY_CODE_TYPES = {
    VALIDATE_EMAIL: 'VALIDATE_EMAIL',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}

export const PLATFOMR_TYPES = {
    GITHUB: 'GITHUB',
    LINKEDIN: 'LINKEDIN',
    FACEBOOK: 'FACEBOOK',
    TWITTER: 'TWITTER',
}

